<?php

/**
 * @file
 * Contains recrutement.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function recrutement_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the recrutement module.
    case 'help.page.recrutement':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function recrutement_theme() {
  $theme = [];
  $theme['recrutement'] = [
    'render element' => 'elements',
    'file' => 'recrutement.page.inc',
    'template' => 'recrutement',
  ];
  $theme['recrutement_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'recrutement.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function recrutement_theme_suggestions_recrutement(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#recrutement'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'recrutement__' . $sanitized_view_mode;
  $suggestions[] = 'recrutement__' . $entity->bundle();
  $suggestions[] = 'recrutement__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'recrutement__' . $entity->id();
  $suggestions[] = 'recrutement__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
