<?php
/**
 * Created by PhpStorm.
 * User: POE 2
 * Date: 09/11/2016
 * Time: 12:42
 */

//hook de test affichant un message lorsque que le cron est lancé
function recrutement_cron()
{
    return drupal_set_message("Le cron a été lance", "status");
}


//hook qui configure le mail d'envoi lorsque le formulaire
function recrutement_mail($key, &$message, $param)
{
    $options = array(
        'langcode' => $message['langcode'],//La langue du courriel
    );

    //Selon cas où la clé est renseigné, on formalise le courriel
    switch ($key) {
        case 'node_insert':
            $message['from'] = \Drupal::config('system.site')->get('mail');//Le mail de l'expéditeur
            $message['subject'] = t('Le sujet du mail ici: @title', array('@title' => $param['title']), $options);//L'objet du courriel
            $message['body'][] = \Drupal\Component\Utility\Html::escape($param['message']);//Le corps du courriel
            $message['path']=\Drupal::service('path.validator');//Le path pour valider le courriel
            break;
    }

//fonction qui envoi le chemin valide dans le courriel
function recrutement_validate_path($element, \Drupal\Core\Form\FormState $form_state)
    {
        $path = $element['#value'];
        if (!empty($path)) {
            if (!(\Drupal::service('path.validator')->isValid($path))) {
                $form_state->setError($element, t('Veuillez indiquer un chemin de redirection valide.'));
            }
        }
    }
}


function recrutement_entity_prepare_form(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Form\FormStateInterface $form_state)
{
    //On affiche un display form different si l'événement est passé
    if ($operation == 'edit' && $entity->getEntityTypeId() == 'node' && $entity->bundle() == 'evenement') {
        $date = time();
        $dateevent = $entity->get('field_date_de_l_evenement')->getValue()[0]['value'];
        if ($date > $dateevent) {
            $storage = \Drupal::getContainer()->get('entity.manager')->getStorage('entity_form_display');
            $form_display = $storage->load('node.evenement.evenement_passe');
            $form_state->getBuildInfo()['callback_object']->setFormDisplay($form_display, $form_state);
        }
    }
}


/*function recrutement_entity_type_alter(array &$entity_types) {
    $a = 1;
}
function recrutement_entity_type_build(array &$entity_types) {
    $a = 1;
}*/
